[project]
name = "simplequoteapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flasgger>=0.9.7.1",
    "flask>=3.1.1",
    "flask-rest>=1.3",
    "flask-restx>=1.3.0",
    "marshmallow>=4.0.0",
]
